name:                netFortune
version:             0.1.0.0
github:              "githubuser/haskell-web-base"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- random
- text
- bytestring
- snap
- hspec
- hspec-snap
- hspec-core
- snap-core
- postgresql-simple
- resource-pool
